# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage:
    displayName: BuildAndPublish
    jobs:
      - job:
        displayName: 'Build Job'
        steps:
          - script: dotnet restore --no-cache
            displayName: 'Restore package'
        
          - script: dotnet build --configuration $(buildConfiguration) --no-restore
            displayName: 'Build package'
        
          - script: dotnet test --no-build --configuration $(buildConfiguration)
            displayName: 'DotNet test'
          - task: DotNetCoreCLI@2
            displayName: 'Unit Test'
            inputs:
              azureSubscription: 'randomtfazspn'
              command: 'test'
              projects: '**/webtest.csproj'
              configuration: $(buildConfiguration)
              
          # - task: WhiteSource@21
          #   inputs:
          #     cwd: '$(System.DefaultWorkingDirectory)'
          #     projectName: 'webapp'
          #   displayName: 'Mend task'
          
          - script: dotnet publish --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)
            displayName: 'DotNet publish'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish build package'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: 
    displayName: ApproveAndDeploy
    jobs:
      - deployment: DeployWeb
        displayName: deploy Web App
        environment: 'SampleDotNet'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@1
                displayName: 'Download build artifact'
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'randomtfazspn'
                  appType: 'webAppLinux'
                  appName: 'mypipletest'
                  package: '$(System.ArtifactsDirectory)/**/*.zip'
                  runtimeStack: 'DOTNETCORE|8.0'
              

              

          

